/**
 * The output of the Discovery stage.
 *
 * Discovery is the first stage of the workflow and the heart of Agency OS: it
 * takes a raw, often vague brief and decodes it into structured decisions. The
 * shape is deliberately narrow — Discovery does not do Brand or Strategy work;
 * it clarifies *what the client actually wants* and *what we still need to ask*.
 *
 * Discovery produces this as the `output` of a {@link StageResult}, so it arrives
 * wrapped in the full Stage Contract (readiness = Brief Clarity, doubts, missing
 * info, recommendations, next step).
 */
export interface DiscoveryOutput {
  /** A clean restatement of what the client actually seems to want. */
  readonly interpretedBrief: string;
  /** The core move: decode vague client words into their likely meaning. */
  readonly decodedSignals: readonly DecodedSignal[];
  /** Questions the operator should ask the client — generated by the AI. */
  readonly openQuestions: readonly OpenQuestion[];
  /** What the AI is assuming, stated so the operator can correct it. */
  readonly assumptions: readonly string[];
}

/** A single piece of vague client feedback, decoded. */
export interface DecodedSignal {
  /** The client's actual words, e.g. "make it premium". */
  readonly clientSaid: string;
  /** The most likely concrete meaning behind those words. */
  readonly likelyMeans: string;
  /** How confident the interpretation is. */
  readonly confidence: SignalConfidence;
}

export type SignalConfidence = "low" | "medium" | "high";

/** A question worth asking the client to raise brief clarity. */
export interface OpenQuestion {
  readonly question: string;
  readonly whyItMatters: string;
}
